# Generated by Django 5.2.7 on 2025-10-28 00:28

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteartist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='favoritetrack',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteartist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='favoritetrack',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoriteartist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteartist',
            name='deezer_id',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteartist',
            name='name',
            field=models.CharField(default='Unknown Artist', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteartist',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriteartist',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='album_cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='album_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='artist_name',
            field=models.CharField(default='Unknown Artist', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='deezer_id',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='title',
            field=models.CharField(default='Unknown Track', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='favoriteartist',
            index=models.Index(fields=['user', 'created_at'], name='music_favor_user_id_a210d5_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritetrack',
            index=models.Index(fields=['user', 'created_at'], name='music_favor_user_id_802ae7_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoriteartist',
            constraint=models.UniqueConstraint(fields=('user', 'deezer_id'), name='uniq_user_artist'),
        ),
        migrations.AddConstraint(
            model_name='favoritetrack',
            constraint=models.UniqueConstraint(fields=('user', 'deezer_id'), name='uniq_user_track'),
        ),
        migrations.RemoveField(
            model_name='favoriteartist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='favoritetrack',
            name='track',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
