# Generated by Django 5.2.7 on 2025-10-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_favoriteartist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteartist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='favoritetrack',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='favoriteartist',
            name='uniq_user_artist',
        ),
        migrations.RemoveConstraint(
            model_name='favoritetrack',
            name='uniq_user_track',
        ),
        migrations.RemoveIndex(
            model_name='favoriteartist',
            name='music_favor_user_id_a210d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='favoritetrack',
            name='music_favor_user_id_802ae7_idx',
        ),
        migrations.RemoveField(
            model_name='favoriteartist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favoritetrack',
            name='user',
        ),
        migrations.AlterField(
            model_name='favoriteartist',
            name='deezer_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='favoritetrack',
            name='deezer_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
