# Generated by Django 5.2.7 on 2025-11-06 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_favoriteartist_user_favoritetrack_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteartist',
            name='deezer_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='favoritetrack',
            name='deezer_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteartist',
            unique_together={('user', 'deezer_id')},
        ),
        migrations.AlterUniqueTogether(
            name='favoritetrack',
            unique_together={('user', 'deezer_id')},
        ),
    ]
