# Generated by Django 5.2.7 on 2025-11-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_favoritealbum'),
        ('music', '0005_alter_favoriteartist_deezer_id_and_more'),
    ]

    operations = [
    ]
