# Generated by Django 5.2.7 on 2025-11-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_rename_artist_favoritealbum_artist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritealbum',
            old_name='cover',
            new_name='album_cover',
        ),
        migrations.RenameField(
            model_name='favoritealbum',
            old_name='title',
            new_name='album_title',
        ),
    ]
