# Generated by Django 5.2.7 on 2025-11-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_rename_cover_favoritealbum_album_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritealbum',
            old_name='album_cover',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='favoritealbum',
            old_name='album_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='favoritealbum',
            name='deezer_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
