# Generated by Django 5.2.7 on 2025-11-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_rename_album_cover_favoritealbum_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtrack',
            name='album_cover',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listtrack',
            name='album_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listtrack',
            name='artist_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='listtrack',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listtrack',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
